name: CI

on:
  push:
    branches:
      - 'master'
      - 'dev'
  pull_request:
    branches:
      - 'master'
      - 'dev'

jobs:
  lint-html:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1.4.2
      with:
        node-version: '12.x'
        
    - name: Install npm packages
      run: npm ci
        
    - name: Test index
      run: npm run lint-html
      
  lint-javascript:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1.4.2
      with:
        node-version: '12.x'
        
    - name: Install npm packages
      run: npm ci
        
    - name: Lint JS
      run: npm run lint-javascript
      
  test-javascript:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1.4.2
      with:
        node-version: '12.x'
      
    - name: Install npm packages
      run: npm ci
        
    - name: Test JS
      run: npm run test-javascript
      