name: CI

on:
  push:
    branches:
      - 'master'
      - 'dev'
  pull_request:
    branches:
      - 'master'
      - 'dev'

jobs:
  lint-html:
    name: "Lint HTML"
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2.1.4
      with:
        node-version: '14'
        
    - name: Install npm packages
      run: npm ci
        
    - name: Lint HTML
      run: npm run lint-html
      
  lint-javascript:
    name: "Lint JS"
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2.1.4
      with:
        node-version: '14'
        
    - name: Install npm packages
      run: npm ci
        
    - name: Lint JS
      run: npm run lint-javascript
      
  test-javascript:
    name: "Test JS"
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2.1.4
      with:
        node-version: '14'
      
    - name: Install npm packages
      run: npm ci
        
    - name: Test JS
      run: npm run test-javascript
      